### PR TITLE
Make an e2e test for new ECL whitelist[strict] logic

### LINKED ISSUE #578: Make an e2e test for new ECL whitelist[strict] logic
Follow up from https://github.com/apptainer/apptainer/pull/577

### PR DESCRIPTION
**Pull request by JasonYangShadow**
Signed-off-by: jason yang <jasonyangshadow@gmail.com>

## Description of the Pull Request (PR):

Make an e2e test for new ECL whitelist[strict] logic

### This fixes or addresses the following GitHub issues:

 - Fixes #578 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by JasonYangShadow** [comment]
@ikaneshiro no hurries, but please help review when you have time 😎

**Comment by JasonYangShadow** [comment]
@DrDaveD no hurries, I know you are quite busy recently, if you have time, may you please help review. Thanks so much!

**Comment by DrDaveD** [comment]
It looks OK to me but I would like @ikaneshiro to review it.

**Review by ikaneshiro — APPROVED** [review]
LGTM

**Pull request merged**
