### PR TITLE
Changing fakeroot from Required to Recommended in the rpm spec to fix #2348

### LINKED ISSUE #2348: Make fakeroot recommended in rpm
Currently, `fakeroot` is required by the `apptainer` rpm.

https://github.com/apptainer/apptainer/blob/20b535379a92372cb62b5b603bb5197dcdbf468d/dist/rpm/apptainer.spec.in#L130

But `apptainer` doesn't actually need the `fakeroot` command to work; if it can't find the command, it will just use root-mapped namespace. Some dists don't provide this tool (not even on SLES15SP6).

Can we change the `Requires:` to `Recommends:`?

### PR DESCRIPTION
**Pull request by arozenfe**
## Description of the Pull Request (PR):

apptainer doesn't actually need the `fakeroot` command to work; if it can't find the command, it will just use root-mapped namespace. Some dists don't even provide this tool. Thus changing the `fakeroot` in the rpm spec file from `Required` to `Recommended`. If `fakeroot` exists in the hosts repository it will be installed, and if it doesn't, `apptainer` will still get installed successfully. 

### This fixes or addresses the following GitHub issues:

 - Fixes #2348

#### Before submitting a PR, make sure you have done the following:

 - Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
 - Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
 - Added tests to validate this PR, linted with make check and tested this PR locally with a make test, and make testall if possible (see CONTRIBUTING.md).
 - Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
 - Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by DrDaveD** [comment]
This change looks OK now, but you had removed the "Before submitting a PR" section, which I have now added back.  We need an entry in the CHANGELOG (in the v1.3.x section) and you need to add yourself to the CONTRIBUTORS file.

There has been a recent addition to the CHANGELOG so you'll need to rebase on the current main to avoid a conflict there.

Maybe there should be a rpmbuild-suse15 ci check too, if you want to make sure nobody breaks the build for that with a future PR.

**Comment by arozenfe** [comment]
I think I did something wrong when I tried to rebase/merge my branches. I'm not sure how to fix it, or how I should have done it. Should I delete my branch and start a new one?

**Comment by arozenfe** [comment]
@DrDaveD I've made the changes, you required, but as I said I think something went wrong with the merge to my branch, I don't know if it it's ok the way it is.

**Comment by DrDaveD** [comment]
No it's not OK.  Please make a fresh branch off of the current main under this name and do `git push -f`.

**Pull request closed without merging**
