### PR TITLE
fix issue apptainer will not read credentials from fallback path

### LINKED ISSUE #1616: Docker credentials not read from `~/.docker/config.json`
### Version of Apptainer

```sh
$ apptainer --version
apptainer version 1.2.2-1.el7
$ 
```

### Expected behavior

If one only has a `~/.docker/config.json` then the credentials should be read from this file path, as [stated in the apptainer documentation](https://apptainer.org/docs/user/1.2/docker_and_oci.html#docker-cli-authentication).

### Actual behavior

Only the file `~/.apptainer/docker-config.json` is searched for credentials.

#### Remove your apptainer docker-config.json
```sh
# for example: rm ~/.apptainer/docker-config.json
```

#### Remove your docker configuration directory
```sh
# for example: rm ~/.docker/config.json
```

#### Login to DockerHub
```sh
sh-4.2$ apptainer remote login -u [elided] docker://docker.io
Password / Token: 
INFO:    Token stored in /[elided]/.apptainer/remote.yaml
sh-4.2$ 
```

NOTE: As we'll see, the token is NOT stored in that file… but that message isn't really the issue.

#### Try to pull a private docker image (this works)
```sh
# Don't need to pull the whole image, so using `timeout` which logs in, but then produces an error while cleaning up
$ timeout 5s apptainer -s build temp.sif docker://somerepo/someimg:sometag
ERROR:   Could not remove bundle: could not remove "/tmp/build-temp-574505820": unlinkat /tmp/build-temp-574505820/rootfs/usr/share/man: directory not empty
$ 
```

#### Move the file containing the token to `~/.docker/config.json`

```sh
$ mkdir ~/.docker
$ mv ~/.apptainer/docker-config.json ~/.docker/config.json
$ 
```

#### (Optional) Verify your username and password are stored within the `~/.docker/config.json`
```sh
$ jq -r '.auths["https://index.docker.io/v1/"].auth' ~/.docker/config.json | base64 -d && echo
[elided]
$ 
```

#### Try to pull the same private image, but using ~/.docker/config.json (should work but doesn't)
```sh
$ timeout 5s apptainer -s build temp.sif docker://somerepo/someimg:sometag
FATAL:   While performing build: conveyor failed to get: while converting reference: reading manifest sometag in docker.io/someimg/sometag: requested access to the resource is denied
$ 
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
$ 
```

### How did you install Apptainer

Was probably installed via RPM by our I/T department.

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

### This fixes or addresses the following GitHub issues:

 - Fixes #1616

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

image

### CODE REVIEW

**Review by DrDaveD — APPROVED** [review]
This looks to me like a good fix, but do we understand why it used to work and it doesn't anymore?  I found one comment in cmd/internal/cli/build.go saying "containers/image falls back to looking for .docker/config.json" so maybe at some point that worked but later stopped?

**Comment by JasonYangShadow** [comment]
> This looks to me like a good fix, but do we understand why it used to work and it doesn't anymore? I found one comment in cmd/internal/cli/build.go saying "containers/image falls back to looking for .docker/config.json" so maybe at some point that worked but later stopped?

I checked that 1.1.9 RPM installed version works
but 1.2.0-rc.1-1 RPM installed version does not work

Successful case:
```
[vagrant@localhost apptainer]$ timeout 5s apptainer --debug build test.sif docker://jasonyangshadow/centos:test
DEBUG   [U=1000,P=8891]    persistentPreRun()            Apptainer version: 1.1.2+822-g2753495
DEBUG   [U=1000,P=8891]    persistentPreRun()            Parsing configuration file /usr/local/etc/apptainer/apptainer.conf
DEBUG   [U=1000,P=8891]    SetBinaryPath()               Setting binary path to /usr/local/libexec/apptainer/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/bin:/usr/local/go/bin:/home/vagrant/.local/bin:/home/vagrant/bin:/usr/local/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG   [U=1000,P=8891]    SetBinaryPath()               Using that path for all binaries
DEBUG   [U=1000,P=8891]    handleConfDir()               /home/vagrant/.apptainer already exists. Not creating.
DEBUG   [U=1000,P=8891]    handleRemoteConf()            Ensuring file permission of 0600 on /home/vagrant/.apptainer/remote.yaml
DEBUG   [U=1000,P=8891]    getCacheParentDir()           environment variable APPTAINER_CACHEDIR not set, using default image cache
DEBUG   [U=1000,P=8891]    newBundle()                   Created temporary directory "/tmp/bundle-temp-1296361326" for the bundle
DEBUG   [U=1000,P=8891]    newBundle()                   Created directory "/tmp/build-temp-4141824409/rootfs" for the bundle
DEBUG   [U=1000,P=8891]    findOnPath()                  Found "mksquashfs" at "/usr/sbin/mksquashfs"
DEBUG   [U=1000,P=8891]    ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=1000,P=8891]    findOnPath()                  Found "mksquashfs" at "/usr/sbin/mksquashfs"
DEBUG   [U=1000,P=8891]    ensureGzipComp()              Gzip compression by default ensured
INFO    [U=1000,P=8891]    Full()                        Starting build...
DEBUG   [U=1000,P=8891]    Get()                         Reference: jasonyangshadow/centos:test
DEBUG   [U=1000,P=8891]    getDockerRefDigest()          docker.GetDigest digest for docker://jasonyangshadow/centos:test is 3984053d904781c0af1f8732db8b9b16f75cc7c0112229e7ddd72edfe5ed3e63
DEBUG   [U=1000,P=8891]    getRefDigest()                GetManifest digest for docker://jasonyangshadow/centos:test is 3984053d904781c0af1f8732db8b9b16f75cc7c0112229e7ddd72edfe5ed3e63
Getting image source signatures
Copying blob 3d698fd0ce1d [==>-----------------------------------] 4.2MiB / 61.5MiB
Copying blob 2d473b07cdd5 [--------------------------------------] 0.0b / 72.6MiB
^CDEBUG   [U=1000,P=8891]    cleanUp()                     Cleaning up "/tmp/build-temp-4141824409/rootfs" and "/tmp/bundle-temp-1296361326"
```

Failed case:
```
[vagrant@localhost apptainer]$ timeout 5s apptainer --debug build test.sif docker://jasonyangshadow/centos:test
DEBUG   [U=1000,P=8913]    persistentPreRun()            Apptainer version: 1.1.2+822-g2753495
DEBUG   [U=1000,P=8913]    persistentPreRun()            Parsing configuration file /usr/local/etc/apptainer/apptainer.conf
DEBUG   [U=1000,P=8913]    SetBinaryPath()               Setting binary path to /usr/local/libexec/apptainer/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/bin:/usr/local/go/bin:/home/vagrant/.local/bin:/home/vagrant/bin:/usr/local/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG   [U=1000,P=8913]    SetBinaryPath()               Using that path for all binaries
DEBUG   [U=1000,P=8913]    handleConfDir()               /home/vagrant/.apptainer already exists. Not creating.
DEBUG   [U=1000,P=8913]    handleRemoteConf()            Ensuring file permission of 0600 on /home/vagrant/.apptainer/remote.yaml
DEBUG   [U=1000,P=8913]    getCacheParentDir()           environment variable APPTAINER_CACHEDIR not set, using default image cache
DEBUG   [U=1000,P=8913]    newBundle()                   Created temporary directory "/tmp/bundle-temp-1497074605" for the bundle
DEBUG   [U=1000,P=8913]    newBundle()                   Created directory "/tmp/build-temp-285418382/rootfs" for the bundle
DEBUG   [U=1000,P=8913]    findOnPath()                  Found "mksquashfs" at "/usr/sbin/mksquashfs"
DEBUG   [U=1000,P=8913]    ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=1000,P=8913]    findOnPath()                  Found "mksquashfs" at "/usr/sbin/mksquashfs"
DEBUG   [U=1000,P=8913]    ensureGzipComp()              Gzip compression by default ensured
INFO    [U=1000,P=8913]    Full()                        Starting build...
DEBUG   [U=1000,P=8913]    Get()                         Reference: jasonyangshadow/centos:test
DEBUG   [U=1000,P=8913]    getRefDigest()                Falling back to GetManifest digest: reading digest test in docker.io/jasonyangshadow/centos: requested access to the resource is denied
DEBUG   [U=1000,P=8913]    cleanUp()                     Cleaning up "/tmp/build-temp-285418382/rootfs" and "/tmp/bundle-temp-1497074605"
FATAL   [U=1000,P=8913]    runBuildLocal()               While performing build: conveyor failed to get: while converting reference: reading manifest test in docker.io/jasonyangshadow/centos: requested access to the resource is denied
```

I am still investigating the root cause.

**Comment by DrDaveD** [comment]
It would be good to also add an e2e test that has the credentials in .docker/config.json instead of .apptainer/docker-config.json.

**Comment by JasonYangShadow** [comment]
> It would be good to also add an e2e test that has the credentials in .docker/config.json instead of .apptainer/docker-config.json.

the really weird thing is that  I can not reproduce this issue by recompiling the code
(reset to commit c90eca71324314608bf9c7043a8bb23583ccd04c) 

on ubuntu 22.04
image

on centos 7
image
image

Previous reproduction is done via directly installing the RPM package on centos 7. 
image
As shown in the above screenshot, docker works as reported, but oras always does not work.
image

I come to guess that `Docker` case works might be related to cache ? From the code perspective, it should not work as the current code won't fallback to query the file `~/.docker/config.json`.

**Comment by JasonYangShadow** [comment]
I also added one test case, in which, we will push & pull oras image using different config.

**Comment by DrDaveD** [comment]
When I rebuild from tag v1.1.9, I definitely still see it reading from ~/.docker/config.json.  I can see it in strace.  But it does not happen with 1.2.2.

**Comment by DrDaveD** [comment]
The behavior difference sees to be in the call to [github.com/containers/image/v5/docker.GetDigest](https://github.com/apptainer/apptainer/blob/5c56b2e7704387cfead422bcf6a9c2dfd9657008/internal/pkg/build/oci/oci.go#L243) but I haven't been able to figure out why the behavior changed.  Maybe we should just forget finding out why and accept that we need the new way of doing it.

Please rebase on the current main due to the CHANGELOG fix.

**Review by cclerget — APPROVED** [review]

**Pull request merged**
