### PR TITLE
Add libnvidia-gpucomp to the list of NVIDIA driver libraries

### PR DESCRIPTION
**Pull request by dadap**
Upcoming versions of the NVIDIA driver will include a new component:

https://forums.developer.nvidia.com/t/new-driver-component-libnvidia-gpucomp/267060

Update the list of NVIDIA driver libraries so that it can be included in the runtime environment along with the others.

## Description of the Pull Request (PR):

Add an upcoming NVIDIA driver library to the existing list of NVIDIA driver libraries

### This fixes or addresses the following GitHub issues:

 - Fixes # N/A

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Review by GodloveD — APPROVED** [review]

**Comment by GodloveD** [comment]
Thank you for this addition @dadap.

**Comment by DrDaveD** [comment]
Please also add a message to the v1.2.x section of the CHANGELOG indicating this change, and add yourself to CONTRIBUTORS.md.

**Comment by dadap** [comment]
> Please also add a message to the v1.2.x section of the CHANGELOG indicating this change, and add yourself to CONTRIBUTORS.md.

Sure thing; I added a second commit for that. Feel free to squash before merging if you prefer.

**Comment by DrDaveD** [comment]
Unfortunately the second commit didn't get the `git -s` on it, causing the DCO check to fail, so you need to undo it and force push.  While you're at it you might as well reset back past both commits and put everything in one commit.

**Comment by dadap** [comment]
Well, at least we know the commit validation is working. :)

Squashed and force-pushed.

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
Thank you.  Please also submit a pull request against the release-1.2 branch that cherry-picks this commit.

**Comment by dadap** [comment]
Sure thing; created #1721. Looks like there was an entry in the changelog in the release-1.2 branch that doesn't show up in main; I put the changelog entry for this change in between that one and the last one that shows up in the version of CHANGELOG.md in main.

**Pull request merged**
