### PR TITLE
Fixes #128 - no warning if ENV override with same value

### LINKED ISSUE #128: Allow both APPTAINER and SINGULARITY env variables to be set without warning
On the current main branch, after #108, a warning is printed whenever a SINGULARITY prefix variable is set, even if the corresponding APPTAINER prefix variable is also set to the same value.  This behavior would prohibit people from writing scripts that work with both apptainer and singularity without having to ignore or suppress warnings.  Change the behavior to only print a warning if the value of the two variables are different, and to print only a debug message if they are the same.

### PR DESCRIPTION
**Pull request by PaulCharlton**
Fixes #128 - no warning if ENV override with same value

if override with new value - emit warning
if override with same value - emit debug message

### CODE REVIEW

**Review by DrDaveD — CHANGES_REQUESTED** [review]
The warning that I see when setting both APPTAINER_TMPDIR and SINGULARITY_TMPDIR to the same value is
```
WARNING: Environment Prefix [SINGULARITY_] has been deprecated in favor of [APPTAINER_] for [SINGULARITY_TMPDIR]
```
I don't see you changing that message here.

**Comment by PaulCharlton** [comment]
@DrDaveD we need to be explicit as to the difference between `APPTAINER_` and `APPTAINERENV_` ... they are two entirely different things

**Comment by PaulCharlton** [comment]
this PR addresses the "APPTAINERENV_" only

**Comment by PaulCharlton** [comment]
added code for `APPTAINER_` prefix
1) warning if deprecated prefix used with different value or standalone
2) debug message if deprecated prefix used with identical value

@DrDaveD

**Review by DrDaveD — CHANGES_REQUESTED** [review]
I compiled the current PR branch and found some problems. 

1. I still see the deprecated warning with SINGULARITY_ & APPTAINER_ prefixes setting the same value:
```
$ SINGULARITY_TMPDIR=/scratch/tmp APPTAINER_TMPDIR=/scratch/tmp apptainer exec docker://alpine true
WARNING: Environment Prefix [SINGULARITY_] has been deprecated in favor of [APPTAINER_] for [SINGULARITY_TMPDIR], using deprecated value [/scratch/tmp]
```

2. With a SINGULARITYENV_ in the deprecated message it should not append the key to prefixedKey, it gets a duplicate of the name:
```
$ SINGULARITYENV_FOO=bar apptainer exec docker://alpine true
WARNING: DEPRECATED USAGE: forwarding SINGULARITYENV_FOOFOO as environment variable will not be supported, use APPTAINERENV_FOO instead
```
+ I also noticed that the message looks very different from the message used with SINGULARITY_ variables as above.  While you're fixing this please make it look more like the other one since I think users will expect consistent behavior for environment variables even if they are processed differently.

3. There is a new warning when an ENV_ variable is overriding something from the environment, e.g.:
```
$ APPTAINERENV_FOO=bar FOO=baz apptainer exec docker://alpine true
WARNING: Environment variable [FOO] already has value [bar], will not forward new value [baz] from parent process environment
```
+ This didn't happen before.  I'm not saying that this alone is necessarily a problem, but it even happens with the exec `-e` option which says to not import anything from the parent environment, and I think that at least is a problem.

4. There should probably be some automated tests added for this functionality.

**Comment by PaulCharlton** [comment]
@DrDaveD all should be ready for review except your point 4 moved to #132

**Review by DrDaveD — APPROVED** [review]
Ok, this is good enough.  I have some more suggested wording changes to the messages but I'll do it as a separate PR.

**Pull request merged**
