### PR TITLE
Missing ` in code multiline block

### PR DESCRIPTION
**Pull request by Davte**
This broke markdown syntax.

### CODE REVIEW

**Comment by DrDaveD** [comment]
Oh, that exposed another error which was found by lintmarkdown this time:
```
INSTALL.md:192 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```sh"]
```
Please add a blank line after 'On CentOS/RHEL:` too.

**Comment by DrDaveD** [comment]
There was a testing failure that has now been fixed in the main branch.  Please rebase.  While you're at it, please squash the two commits into one.

**Comment by Davte** [comment]
> There was a testing failure that has now been fixed in the main branch. Please rebase. While you're at it, please squash the two commits into one.

I hope I did it well. I run:
```bash
git remote add upstream git@github.com:apptainer/apptainer.git
git fetch upstream
git merge-base patch-1  upstream/main
```
Then rebased and squashed the two commits, then pushed with `--force-with-lease` option.

**Comment by DrDaveD** [comment]
It does look right.  This is how I usually do it:
```
git fetch upstream
git checkout main
git merge upstream/main
git checkout mybranch
git rebase main
```

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
Thanks for your contribution!  If you don't mind, please make one more PR that cherry-picks this commit to the 1.1 branch so the INSTALL.md will be correct there too.  #803 is an example, you could follow that pattern.

**Comment by Davte** [comment]
Thank you!

**Pull request merged**
