### PR TITLE
Check for errors in call to copyDeviceContents()

### LINKED ISSUE #1711: Apptainer fails to check for errors during copy to encrypted disk
### Version of Apptainer

```shell
# apptainer --version
apptainer version 1.2.0~rc.1-1
```

I used this version to match a production environment; but the problem appears to exist in the current version of Apptainer as well.

https://github.com/apptainer/apptainer/blob/main/internal/pkg/util/crypt/crypt_dev.go#L206

### Expected behavior

If Apptainer is copying squashfs to the encrypted virtual disk and the storage backing the encrypted virtual disk fills up, Apptainer should stop building and report the error.

### Actual behavior

Apptainer proceeds with building a corrupted sif.

```
DEBUG   [U=0,P=17607]      Open()                        Running /sbin/cryptsetup /sbin/cryptsetup open --batch-mode --type luks2 --key-file - /dev/loop0 4f458d68-88c4-4b12-95d8-37fa4b8e5c13                                            
DEBUG   [U=0,P=17607]      Open()                        Successfully opened encrypted device /dev/loop0
DEBUG   [U=0,P=17607]      copyDeviceContents()          Copying /tmp/bundle-temp-2153700816/squashfs-2433701275 to /dev/mapper/4f458d68-88c4-4b12-95d8-37fa4b8e5c13, size 1050845184                                                     
[Sep29 00:31] lo_write_bvec: 41679 callbacks suppressed
[  +0.000010] loop: Write error at byte offset 896798720, length 4096.
[  +0.006841] loop: Write error at byte offset 896802816, length 4096.
[  +0.001085] loop: Write error at byte offset 896806912, length 4096.
[  +0.001067] loop: Write error at byte offset 896811008, length 4096.
[  +0.001106] loop: Write error at byte offset 896815104, length 4096.
[  +0.001034] loop: Write error at byte offset 896819200, length 4096.
[  +0.001004] loop: Write error at byte offset 896823296, length 4096.
[  +0.001009] loop: Write error at byte offset 896827392, length 4096.
[  +0.000995] loop: Write error at byte offset 896831488, length 4096.
[  +0.001080] loop: Write error at byte offset 896835584, length 4096.
[  +0.001218] print_req_error: 41679 callbacks suppressed
[  +0.000012] blk_update_request: I/O error, dev loop0, sector 1751624 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0                                                                                                              
[  +0.002198] buffer_io_error: 41679 callbacks suppressed
[  +0.000014] Buffer I/O error on dev dm-2, logical block 214857, lost async page write
[  +0.002084] blk_update_request: I/O error, dev loop0, sector 1751632 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0                                                                                                              
[  +0.000988] Buffer I/O error on dev dm-2, logical block 214858, lost async page write
[  +0.001007] blk_update_request: I/O error, dev loop0, sector 1751640 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0                                                                                                              
[  +0.001165] Buffer I/O error on dev dm-2, logical block 214859, lost async page write
[  +0.001070] blk_update_request: I/O error, dev loop0, sector 1751648 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0                                                                                                              
[  +0.000229] blk_update_request: I/O error, dev loop0, sector 1751560 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0                                                                                                              
[  +0.000881] Buffer I/O error on dev dm-2, logical block 214860, lost async page write
[  +0.000988] Buffer I/O error on dev dm-2, logical block 214849, lost async page write
[  +0.000974] blk_update_request: I/O error, dev loop0, sector 1751656 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0                                                                                                              
[  +0.000945] blk_update_request: I/O error, dev loop0, sector 1751568 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0                                                                                                              
[  +0.001000] Buffer I/O error on dev dm-2, logical block 214861, lost async page write
[  +0.000007] blk_update_request: I/O error, dev loop0, sector 1751664 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0                                                                                                              
[  +0.000003] Buffer I/O error on dev dm-2, logical block 214862, lost async page write
[  +0.000003] blk_update_request: I/O error, dev loop0, sector 1751672 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0                                                                                                              
[  +0.000002] Buffer I/O error on dev dm-2, logical block 214863, lost async page write
[  +0.000003] blk_update_request: I/O error, dev loop0, sector 1751680 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0                                                                                                              
[  +0.000002] Buffer I/O error on dev dm-2, logical block 214864, lost async page write
[  +0.000939] Buffer I/O error on dev dm-2, logical block 214850, lost async page write
DEBUG   [U=0,P=17607]      EncryptFilesystem()           Running /sbin/cryptsetup /sbin/cryptsetup close 4f458d68-88c4-4b12-95d8-37fa4b8e5c13                                                                                             
VERBOSE [U=0,P=17607]      Full()                        Build complete: /local/alpine-fat.sif
DEBUG   [U=0,P=17607]      cleanUp()                     Cleaning up "/tmp/build-temp-3059712615/rootfs" and "/tmp/bundle-temp-2153700816"                                                                                                
INFO    [U=0,P=17607]      runBuild()                    Build complete: /local/alpine-fat.sif
```

```shell
# apptainer run --pem-path /root/apptainer_rsa /local/alpine-fat.sif 
FATAL:   container creation failed: mount hook function failure: mount /proc/self/fd/9->/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/9: kernel reported a bad superblock for squashfs image partition, possible causes are that your kernel doesn't support the compression algorithm or the image is corrupted
```

If the `.sif` happens to be being built on the same disk as `/tmp` then it notices disk-full when building the sif and fails appropriately. But if the `.sif` is being written to a different disk which still has space, then it produces a corrupted image.

### Steps to reproduce this behavior

* Build an encrypted container
* `/tmp` should have enough space to build the initial squashfs
* but not enough space to hold the crypt copy

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

Again, this was to match a production environment; but the error is clearly that Apptainer isn't checking for errors returned from `copyDeviceContents()` at https://github.com/apptainer/apptainer/blob/main/internal/pkg/util/crypt/crypt_dev.go#L206

### How did you install Apptainer

RPMs from GitHub releases.

### PR DESCRIPTION
**Pull request by anderbubble**
## Description of the Pull Request (PR):

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

### This fixes or addresses the following GitHub issues:

 - Fixes #1711

### CODE REVIEW

**Review by cclerget — APPROVED** [review]

**Comment by DrDaveD** [comment]
Closing & reopening to wake up CI checks

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
Usually we submit to main branch and then backport, but after releases we do always merge the release branch into the main branch so this will get moved forward then.

**Comment by anderbubble** [comment]
@DrDaveD I originally had it on main; but I wasn't certain where to put it in the changelog then, so figured submitting it to this release and letting it get merged into main from here made the most sense from a changelog perspective. Happy to submit another PR if you'd like.

**Comment by DrDaveD** [comment]
It's alright, it will get merged into main after the 1.2.4 release.

**Pull request merged**
