### PR TITLE
Update contributors md

### PR DESCRIPTION
**Pull request by nyue**
Adding myself to contributor list

Signed-off-by: Nicholas Yue <yue.nicholas@gmail.com>

### CODE REVIEW

**Comment by DrDaveD** [comment]
So it is good that you made this as a separate branch.  It does show your previous commit too though.  That's because you had put that commit into your main branch before you made this branch.  Generally it's better to leave your main branch clear of personal commits, only using it for merging commits in from upstream as they come along.  So what I recommend you do now to get into that state is:
```
git checkout update_contributors_md
git branch -D main
git checkout -b main origin/main
git checkout -
git branch -m show_docker_hash
git push
```
Then make a new PR from your show_docker_hash branch (which includes both commits) and close your other two PRs.

**Comment by nyue** [comment]
The last push has an error

```shell
nyue@Compaq-8200-Elite:~/projects/apptainer/nyue/apptainer_git$ git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 753 bytes | 753.00 KiB/s, done.
From github.com:nyue/apptainer
 * [new branch]          update_contributors_md -> origin/update_contributors_md
Already up to date.
nyue@Compaq-8200-Elite:~/projects/apptainer/nyue/apptainer_git$ git checkout update_contributors_md
Branch 'update_contributors_md' set up to track remote branch 'update_contributors_md' from 'origin'.
Switched to a new branch 'update_contributors_md'
nyue@Compaq-8200-Elite:~/projects/apptainer/nyue/apptainer_git$ git branch -D main
Deleted branch main (was 79ede99d4).
nyue@Compaq-8200-Elite:~/projects/apptainer/nyue/apptainer_git$ git checkout -b main origin/main
Branch 'main' set up to track remote branch 'main' from 'origin'.
Switched to a new branch 'main'
nyue@Compaq-8200-Elite:~/projects/apptainer/nyue/apptainer_git$ git checkout -
Switched to branch 'update_contributors_md'
Your branch is up to date with 'origin/update_contributors_md'.
nyue@Compaq-8200-Elite:~/projects/apptainer/nyue/apptainer_git$ git branch -m show_docker_hash
nyue@Compaq-8200-Elite:~/projects/apptainer/nyue/apptainer_git$ git push
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push origin HEAD:update_contributors_md

To push to the branch of the same name on the remote, use

    git push origin HEAD

To choose either option permanently, see push.default in 'git help config'.

```

**Comment by DrDaveD** [comment]
Ok then use
```
git push origin HEAD
```

**Comment by DrDaveD** [comment]
Actually I gave you some bad instructions for recreating your main branch.  To do that properly, starting from a branch other than main do:
```
git branch -D main
git checkout -b main upstream/main
git push origin -f --set-upstream
```

**Comment by nyue** [comment]
The checkout failed

```shell
nyue@Compaq-8200-Elite:~/projects/apptainer/nyue/apptainer_git$ git status
On branch show_docker_hash
Your branch is up to date with 'origin/update_contributors_md'.

nothing to commit, working tree clean
nyue@Compaq-8200-Elite:~/projects/apptainer/nyue/apptainer_git$ git branch -D main
Deleted branch main (was 79ede99d4).
nyue@Compaq-8200-Elite:~/projects/apptainer/nyue/apptainer_git$ git checkout -b main upstream/main
fatal: 'upstream/main' is not a commit and a branch 'main' cannot be created from it
```

**Comment by DrDaveD** [comment]
You must not have an upstream remote set up as is standard practice when making PRs.  That can be done with
```
git remote add upstream https://github.com/apptainer/apptainer.git
git fetch upstream
```

**Comment by nyue** [comment]
Thank you @DrDaveD 

I have added the upstream as advised.

I have also finish the previous instructions

```
git checkout -b main upstream/main
git push origin -f --set-upstream
```

**Pull request closed without merging**
