### PR TITLE
Fixes #53 - remove commercial "remote build" and subsequent dead code from build and tests

### LINKED ISSUE #53: remove dependencies on remote commercial services (build) for compliance with LF open-source license
remove dependencies on remote commercial services for compliance with LF open-source license

* remote library
* remote builder
* remote key server

target release: Apptainer v1.0.0

### PR DESCRIPTION
**Pull request by PaulCharlton**
Fixes #53 - (partial) as to remote build

remove commercial "remote build" and subsequent dead code from build and tests

### CODE REVIEW

**Comment by PaulCharlton** [comment]
do not merge until after #54 is merged to `main`

**Comment by DrDaveD** [comment]
#54 is merged, please rebase so we can see the differences better

**Comment by PaulCharlton** [comment]
@DrDaveD because of how I submitted the commits, this auto-rebased when you merged the previous PR to main

ready for review

**Comment by DrDaveD** [comment]
That's odd, they still show for me, for example:
Screen Shot 2021-12-12 at 3 13 53 PM

**Review by ikaneshiro — APPROVED** [review]
FWIW, this MR needs to be rebased for the Github diff to only show the changes WRT the new `main` branch, but there should be no merge conflicts since the first commit on this branch is identical to the merged commit on main. In order to review this I have looked just that the second commit diff: https://github.com/apptainer/apptainer/pull/60/commits/3bff016776437c74e92777d4c6f08a28895d7122

lgtm

**Pull request merged**
