### PR TITLE
Sign/Verify with Non-PGP Key Material, from sylabs 1120

### PR DESCRIPTION
**Pull request by edytuk**
This pulls in sylabs PR

- sylabs/singularity#1120
 which related to
- sylabs/singularity#1095

The original PR description was:
> Add `--key` option to `singularity sign` and `singularity verify`, which expect PEM-encoded key material that will be used to sign/verify the image. Add end-to-end tests to cover `--key` usage.
> 
> Extend `internal/app/singularity` package to support signing with a `signature.Signer` and verifying with a `signature.Verifier`.
> 
> Centralize test keys and images that are used by multiple packages to `test/`.

### CODE REVIEW

**Comment by DrDaveD** [comment]
e2e tests are currently failing due to a [problem with all dockerhub ubuntu images](https://github.com/docker-library/official-images/pull/13950).  Hopefully it will get resolved soon.

**Comment by cjdcordeiro** [comment]
should be fixed now :wink:

**Comment by DrDaveD** [comment]
The corresponding documentation is also waiting at apptainer/apptainer-userdocs#170.

**Review by GodloveD — APPROVED** [review]
After spending some time thinking about this and playing with it I think that I support merging it into Apptainer.  But once we get all of the pieces merged in, I will raise some issues to discuss how we can improve the user experience.  

For now, I will just say the following.  If we are going to add this, we must also get the following changes (and maybe others that I did not find) from the Singularity repo into the Apptainer PR pipeline.

https://github.com/sylabs/singularity/pull/1139
https://github.com/sylabs/singularity/pull/1183
https://github.com/sylabs/singularity/pull/1213

As long as we can do that I support this PR.

**Comment by DrDaveD** [comment]
Ian agreed in the meeting today to go ahead with the merge.

**Review by DrDaveD — APPROVED** [review]

**Pull request merged**
