### PR TITLE
Enhancement to debug log to show source docker image hash

### PR DESCRIPTION
**Pull request by nyue**
## Description of the Pull Request (PR):

Print out the source docker image hash to maintain a paper trail of the input image that was used.

This allows us to prove the provenance of the output container.

### This fixes or addresses the following GitHub issues:

 - Fixes #1754

Signed-off-by: Nicholas Yue <yue.nicholas@gmail.com>

### CODE REVIEW

**Comment by DrDaveD** [comment]
Thanks for the contribution.  As a first time contributor, please also add yourself to CONTRIBUTORS.md.

**Comment by DrDaveD** [comment]
Since this is only a change to debug logging, we don't need to mention this change in CHANGELOG.md like we usually do.

**Comment by nyue** [comment]
> Thanks for the contribution. As a first time contributor, please also add yourself to CONTRIBUTORS.md.

What is the easiest way to add to CONTRIBUTORS.md? Submit a new PR ?

**Comment by DrDaveD** [comment]
No, you can included in this PR.  Either redo the first commit or add another.  If you add another I will squash them into one when I merge the PR.

**Pull request closed without merging**
